### PR TITLE
Fix ILogger::operator<< when called on list<string>

### LINKED ISSUE #125: LogWrapper::<<(list) does not behave like LogWrapper::<<(string) used on each element of the list
Calling `info() << someList` should be identical to calling `info() << element` on each element of `someList`.

This is not the case because when used on a list, the string is concatenated with `\n` and the logging callback is called once. Instead, the logging  callback should be called for each line and we shouldn't assume anything on the "newline" character.

### PR DESCRIPTION
**Pull request by dawagner**
Calling info() << someList should be identical to calling info() << element on
each element of someList.

This was not the case because when used on a list, the string was concatenated
with \n and the logging callback called once. Instead, the logging callback
is now called for each line.

Fixes #125.

Signed-off-by: David Wagner <david.wagner@intel.com>

### CODE REVIEW

**Comment by dawagner** [comment]
@krocard @clero @OznOg please review.

**Comment by dawagner** [comment]
Build breaks because the skeleton plugin is not explicitly compiled with C++11 and ILogger.h now requires it.

File: parameter/log/include/log/LogWrapper.h [hunk 1]
```diff
@@ -71,11 +71,11 @@ class LogWrapper
...
     {
-        if (!mLog.str().empty()) {
-            if(isWarning) {
-                mLogger.warning(mProlog + mLog.str());
-            } else {
-                mLogger.info(mProlog + mLog.str());
+        auto logfunc = isWarning ? &ILogger::warning : &ILogger::info;
+
+        for (auto& log : mLogs) {
+            if (!log.str().empty()) {
```
Comment (krocard) [inline parameter/log/include/log/LogWrapper.h]: Are you sure this empty test is still useful ? A stream string is only created if there is things to put in.

Comment (dawagner) [inline parameter/log/include/log/LogWrapper.h]: right.

File: parameter/log/include/log/LogWrapper.h [hunk 2]
```diff
@@ -83,33 +83,38 @@ class LogWrapper
...
      */
     template <class T>
     LogWrapper& operator<<(const T &log)
     {
-        mLog << log;
+        if (mLogs.empty()) {
+            mLogs.emplace_back();
+        }
+
+        mLogs.back() << log;
```
Comment (krocard) [inline parameter/log/include/log/LogWrapper.h]: maybe we could add std::to_string instead of an ostringstream ?
... Never mind, `std::to_string(std::string)` <=> `id` does not exist. Unfortunately.

File: parameter/log/include/log/LogWrapper.h [hunk 3]
```diff
@@ -71,45 +71,48 @@ class LogWrapper
     /** Class destructor */
     ~LogWrapper()
     {
-        if (!mLog.str().empty()) {
-            if(isWarning) {
-                mLogger.warning(mProlog + mLog.str());
-            } else {
-                mLogger.info(mProlog + mLog.str());
-            }
+        auto logfunc = isWarning ? &ILogger::warning : &ILogger::info;
```
Comment (clero) [inline parameter/log/include/log/LogWrapper.h]: as it depends on the template argument, shouldn't logfunc be static?

**Comment by clero** [comment]
:+1:
